apiVersion: v1
kind: Service
metadata:
  name: {{.Value.appName}}
spec:
  type: {{.Values.serviceType}}
  selector:
    app: {{.Value.appName}}
  ports:
  - protocol: TCP
    port: {{.Values.port}}
    targetPort: {{.Values.targetPort}}