apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{.Values.appName}}
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore.yaml
    target:
      name: {{.Values.appName}}
    dataFrom:
    - extract:
        key: {{.Values.appName}}    